
export const MAIL_CONFIG_FETCH = "MAIL_CONFIG_FETCH";
export const MAIL_CONFIG_APPEND = "MAIL_CONFIG_APPEND";
export const MAIL_CONFIG_UPDATE = "MAIL_CONFIG_UPDATE";
export const MAIL_CONFIG_DESTORY = "MAIL_CONFIG_DESTORY";
