
DROP INDEX IF EXISTS [IX_FileID] ON [dbo].[Column]
GO

CREATE NONCLUSTERED INDEX [IX_FileID] ON [dbo].[Column]
(
	[FileID] ASC
)
INCLUDE ( 	[ColumnID],
	[ColumLabel]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
