Dear User, 
<br />
<br/>

For $Model.PlatePlanName$ [$Model.Remark$], UTM is not able to create observation records due to too many columns currently open in the field(s) in Phenome.<br/>
Please delete all field level columns that are not needed in this/those field(s), and check if the status of the plate-plan in UTM move from "readytoSync" to "Completed".<br/>
After removing enough columns (at all levels of the field(s)), you will receive an email when all the marker results are in Phenome.<br/><br/>

Best Regards, <br/>
UTM